#! /usr/bin/bash

if [ "$1" = "spotify" ];
then
	curl -sS https://download.spotify.com/debian/pubkey_0D811D58.gpg | sudo apt-key add -
	echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list
	sudo apt update
	sudo apt install spotify-client
elif [ "$1" = "google-chrome" ]
then
	wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -O chrome.deb
	sudo dpkg -i chrome.deb; sudo apt -f install;
	rm -rf chrome.deb
elif [ "$1" = "vscode" ]
then
	wget https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64 -O code.deb
	sudo dpkg -i code.deb; sudo apt -f install;
	rm -rf code.deb
elif [ "$1" = "obs" ]
then
	sudo apt install ffmpeg
	sudo add-apt-repository ppa:obsproject/obs-studio
	sudo apt update
	sudo apt install obs-studio
elif [ "$1" = "atom" ]
then
	wget https://atom.io/download/deb -O atom.deb
	sudo dpkg -i atom.deb; sudo apt -f install;
	rm -rf atom.deb
elif [ "$1" = "sublime" ]
then
	wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
	sudo apt-get install apt-transport-https
	echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
	sudo apt-get update
	sudo apt-get install sublime-text
elif [ "$1" = "rust" ]
then
	curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
elif [ "$1" = "insomnia" ]
then
	echo "deb https://dl.bintray.com/getinsomnia/Insomnia /" \
    | sudo tee -a /etc/apt/sources.list.d/insomnia.list
	wget --quiet -O - https://insomnia.rest/keys/debian-public.key.asc \
    | sudo apt-key add -
	sudo apt-get update
	sudo apt-get install insomnia
elif [ "$1" = "vivaldi" ]
then
	wget https://downloads.vivaldi.com/stable/vivaldi-stable_3.6.2165.40-1_amd64.deb -O vivaldi.deb
	sudo dpkg -i vivaldi.deb; sudo apt -f install;
	rm -rf vivaldi.deb
elif [ "$1" = "edge" ]
then
	wget https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-dev/microsoft-edge-dev_90.0.803.0-1_amd64.deb -O edge.deb
	sudo dpkg -i edge.deb; sudo apt -f install;
	rm -rf edge.deb
elif [ "$1" = "ms-teams" ]
then
	wget https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/teams_1.3.00.30857_amd64.deb -O teams.deb
	sudo dpkg -i teams.deb; sudo apt -f install;
	rm -rf teams.deb
elif [ "$1" = "brave" ]
then
	sudo apt install apt-transport-https curl gnupg
	curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -
	echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list
	sudo apt update; sudo apt install brave-browser -y
elif [ "$1" = "discord" ]
then
	wget https://dl.discordapp.net/apps/linux/0.0.13/discord-0.0.13.deb -O discord.deb
	sudo dpkg -i discord.deb; sudo apt -f install;
	rm -rf discord.deb
fi
